BankWithHtree.o: BankWithHtree.cpp BankWithHtree.h Bank.h FunctionUnit.h \
 Technology.h typedef.h InputParameter.h constant.h MemCell.h Mat.h \
 SubArray.h RowDecoder.h OutputDriver.h Precharger.h SenseAmp.h Mux.h \
 PredecodeBlock.h BasicDecoder.h Comparator.h TSV.h formula.h global.h \
 Wire.h
BasicDecoder.o: BasicDecoder.cpp BasicDecoder.h FunctionUnit.h \
 Technology.h typedef.h InputParameter.h constant.h MemCell.h \
 OutputDriver.h formula.h global.h Wire.h SenseAmp.h
InputParameter.o: InputParameter.cpp InputParameter.h typedef.h global.h \
 Technology.h constant.h MemCell.h Wire.h SenseAmp.h FunctionUnit.h
formula.o: formula.cpp formula.h Technology.h typedef.h InputParameter.h \
 constant.h MemCell.h
FunctionUnit.o: FunctionUnit.cpp FunctionUnit.h Technology.h typedef.h \
 InputParameter.h constant.h MemCell.h formula.h
Bank.o: Bank.cpp Bank.h FunctionUnit.h Technology.h typedef.h \
 InputParameter.h constant.h MemCell.h Mat.h SubArray.h RowDecoder.h \
 OutputDriver.h Precharger.h SenseAmp.h Mux.h PredecodeBlock.h \
 BasicDecoder.h Comparator.h TSV.h formula.h global.h Wire.h
SubArray.o: SubArray.cpp SubArray.h FunctionUnit.h Technology.h typedef.h \
 InputParameter.h constant.h MemCell.h RowDecoder.h OutputDriver.h \
 Precharger.h SenseAmp.h Mux.h formula.h global.h Wire.h
Technology.o: Technology.cpp Technology.h typedef.h InputParameter.h \
 constant.h MemCell.h
BankWithoutHtree.o: BankWithoutHtree.cpp BankWithoutHtree.h Bank.h \
 FunctionUnit.h Technology.h typedef.h InputParameter.h constant.h \
 MemCell.h Mat.h SubArray.h RowDecoder.h OutputDriver.h Precharger.h \
 SenseAmp.h Mux.h PredecodeBlock.h BasicDecoder.h Comparator.h TSV.h \
 formula.h global.h Wire.h
Mux.o: Mux.cpp Mux.h FunctionUnit.h Technology.h typedef.h \
 InputParameter.h constant.h MemCell.h global.h Wire.h SenseAmp.h \
 formula.h
Result.o: Result.cpp Result.h BankWithHtree.h Bank.h FunctionUnit.h \
 Technology.h typedef.h InputParameter.h constant.h MemCell.h Mat.h \
 SubArray.h RowDecoder.h OutputDriver.h Precharger.h SenseAmp.h Mux.h \
 PredecodeBlock.h BasicDecoder.h Comparator.h TSV.h formula.h global.h \
 Wire.h BankWithoutHtree.h macros.h
Mat.o: Mat.cpp Mat.h FunctionUnit.h Technology.h typedef.h \
 InputParameter.h constant.h MemCell.h SubArray.h RowDecoder.h \
 OutputDriver.h Precharger.h SenseAmp.h Mux.h PredecodeBlock.h \
 BasicDecoder.h Comparator.h TSV.h formula.h global.h Wire.h
Comparator.o: Comparator.cpp Comparator.h FunctionUnit.h Technology.h \
 typedef.h InputParameter.h constant.h MemCell.h global.h Wire.h \
 SenseAmp.h formula.h
PredecodeBlock.o: PredecodeBlock.cpp PredecodeBlock.h FunctionUnit.h \
 Technology.h typedef.h InputParameter.h constant.h MemCell.h \
 RowDecoder.h OutputDriver.h BasicDecoder.h formula.h global.h Wire.h \
 SenseAmp.h
Precharger.o: Precharger.cpp Precharger.h FunctionUnit.h Technology.h \
 typedef.h InputParameter.h constant.h MemCell.h OutputDriver.h formula.h \
 global.h Wire.h SenseAmp.h
RowDecoder.o: RowDecoder.cpp RowDecoder.h FunctionUnit.h Technology.h \
 typedef.h InputParameter.h constant.h MemCell.h OutputDriver.h formula.h \
 global.h Wire.h SenseAmp.h
MemCell.o: MemCell.cpp MemCell.h typedef.h formula.h Technology.h \
 InputParameter.h constant.h global.h Wire.h SenseAmp.h FunctionUnit.h \
 macros.h
SenseAmp.o: SenseAmp.cpp SenseAmp.h FunctionUnit.h Technology.h typedef.h \
 InputParameter.h constant.h MemCell.h formula.h global.h Wire.h
Wire.o: Wire.cpp Wire.h typedef.h SenseAmp.h FunctionUnit.h Technology.h \
 InputParameter.h constant.h MemCell.h global.h formula.h
TSV.o: TSV.cpp TSV.h formula.h Technology.h typedef.h InputParameter.h \
 constant.h MemCell.h global.h Wire.h SenseAmp.h FunctionUnit.h
main.o: main.cpp InputParameter.h typedef.h MemCell.h RowDecoder.h \
 FunctionUnit.h Technology.h constant.h OutputDriver.h Precharger.h \
 SenseAmp.h BasicDecoder.h PredecodeBlock.h SubArray.h Mux.h Mat.h \
 Comparator.h TSV.h formula.h global.h Wire.h BankWithHtree.h Bank.h \
 BankWithoutHtree.h Result.h macros.h
OutputDriver.o: OutputDriver.cpp OutputDriver.h FunctionUnit.h \
 Technology.h typedef.h InputParameter.h constant.h MemCell.h global.h \
 Wire.h SenseAmp.h formula.h
