MODULE = . /usr/share/Modules/init/sh; module use /usr/cots/modulefiles; module load licenses/cadence


VIRTUOSO = tools/virtuoso/IC6.18.080
SPECTRE  = tools/spectre/15.10.518

run:
	@$(MODULE) $(VIRTUOSO) $(SPECTRE); virtuoso &
